import { describe, expect, it } from 'vitest';
import {
  hasValidWeeklyPlanObject,
  mergeBaselineWithRatedIds,
  shouldAutoGenerateWeeklyPlan
} from './planSync';

describe('planSync helpers', () => {
  it('treats a rest-day plan as a valid weekly plan object', () => {
    const plan = {
      monday: null,
      tuesday: { title: 'Run' },
      wednesday: null,
      thursday: { title: 'Tempo' },
      friday: null,
      saturday: null,
      sunday: { title: 'Long Run' }
    };

    expect(hasValidWeeklyPlanObject(plan)).toBe(true);
  });

  it('merges baseline IDs with rated IDs without duplicates', () => {
    const merged = mergeBaselineWithRatedIds(
      [123, '124', '125'],
      [{ activity_id: 124 }, { activity_id: '126' }, { activity_id: null }]
    );

    expect(merged).toEqual(['123', '124', '125', '126']);
  });

  it('does not auto-generate when a valid weekly plan already exists', () => {
    const shouldGenerate = shouldAutoGenerateWeeklyPlan({
      plan: {
        monday: null,
        tuesday: { title: 'Run' },
        wednesday: null,
        thursday: null,
        friday: null,
        saturday: null,
        sunday: null
      },
      weekKey: '2026-03-23',
      availableApiKey: 'key',
      activityCount: 12,
      localAutoGeneratedWeekKey: null
    });

    expect(shouldGenerate).toBe(false);
  });

  it('does not auto-generate if server marker already says this week was auto-generated', () => {
    const shouldGenerate = shouldAutoGenerateWeeklyPlan({
      plan: {
        _generationMeta: { autoGeneratedWeekKey: '2026-03-23' }
      },
      weekKey: '2026-03-23',
      availableApiKey: 'key',
      activityCount: 12,
      localAutoGeneratedWeekKey: null
    });

    expect(shouldGenerate).toBe(false);
  });
});
