export const WEEK_PLAN_DAYS = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];

export const hasValidWeeklyPlanObject = (plan) => {
  if (!plan || typeof plan !== 'object') return false;
  return WEEK_PLAN_DAYS.some((day) => Object.prototype.hasOwnProperty.call(plan, day));
};

export const mergeBaselineWithRatedIds = (baselineIds = [], ratingRows = []) => {
  const baseline = Array.isArray(baselineIds) ? baselineIds.map((id) => String(id)) : [];
  const rated = Array.isArray(ratingRows)
    ? ratingRows.map((row) => String(row?.activity_id ?? '')).filter(Boolean)
    : [];
  return [...new Set([...baseline, ...rated])];
};

export const shouldAutoGenerateWeeklyPlan = ({
  plan,
  weekKey,
  availableApiKey,
  activityCount,
  localAutoGeneratedWeekKey
}) => {
  if (!availableApiKey || activityCount <= 0) return false;
  if (hasValidWeeklyPlanObject(plan)) return false;
  if (!weekKey) return false;

  const serverAutoGeneratedWeekKey = plan?._generationMeta?.autoGeneratedWeekKey || null;
  if (serverAutoGeneratedWeekKey === weekKey) return false;
  if (localAutoGeneratedWeekKey === weekKey) return false;
  return true;
};
